In [5]:
import pandas as pd
import kaggle
import sklearn.datasets as dt
import zipfile
import numpy as np

# LOAD DATA

In [2]:
! kaggle competitions download -c house-prices-advanced-regression-techniques

Downloading house-prices-advanced-regression-techniques.zip to C:\Users\Beon\Documents\github-Kaggle-Competition\Category\Getting Started

  0%|          | 0.00/199k [00:00<?, ?B/s]
100%|##########| 199k/199k [00:00<00:00, 539kB/s]
100%|##########| 199k/199k [00:00<00:00, 537kB/s]

In [6]:
zf = zipfile.ZipFile('house-prices-advanced-regression-techniques.zip')

In [7]:
zf.filelist

[<ZipInfo filename='data_description.txt' compress_type=deflate file_size=13370 compress_size=4446>,
 <ZipInfo filename='sample_submission.csv' compress_type=deflate file_size=31939 compress_size=15648>,
 <ZipInfo filename='test.csv' compress_type=deflate file_size=451405 compress_size=87058>,
 <ZipInfo filename='train.csv' compress_type=deflate file_size=460676 compress_size=96055>]

In [8]:
df_train = pd.read_csv(zf.open('train.csv'))

In [9]:
df_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# Data Description

- SalePrice - the property's sale price in dollars. This is the target variable that you're trying to predict.
- MSSubClass: The building class
- MSZoning: The general zoning classification
- LotFrontage: Linear feet of street connected to property
- LotArea: Lot size in square feet
- Street: Type of road access
- Alley: Type of alley access
- LotShape: General shape of property
- LandContour: Flatness of the property
- Utilities: Type of utilities available
- LotConfig: Lot configuration
- LandSlope: Slope of property
- Neighborhood: Physical locations within Ames city limits
- Condition1: Proximity to main road or railroad
- Condition2: Proximity to main road or railroad (if a second is present)
- BldgType: Type of dwelling
- HouseStyle: Style of dwelling
- OverallQual: Overall material and finish quality
- OverallCond: Overall condition rating
- YearBuilt: Original construction date
- YearRemodAdd: Remodel date
- RoofStyle: Type of roof
- RoofMatl: Roof material
- Exterior1st: Exterior covering on house
- Exterior2nd: Exterior covering on house (if more than one material)
- MasVnrType: Masonry veneer type
- MasVnrArea: Masonry veneer area in square feet
- ExterQual: Exterior material quality
- ExterCond: Present condition of the material on the exterior
- Foundation: Type of foundation
- BsmtQual: Height of the basement
- BsmtCond: General condition of the basement
- BsmtExposure: Walkout or garden level basement walls
- BsmtFinType1: Quality of basement finished area
- BsmtFinSF1: Type 1 finished square feet
- BsmtFinType2: Quality of second finished area (if present)
- BsmtFinSF2: Type 2 finished square feet
- BsmtUnfSF: Unfinished square feet of basement area
- TotalBsmtSF: Total square feet of basement area
- Heating: Type of heating
- HeatingQC: Heating quality and condition
- CentralAir: Central air conditioning
- Electrical: Electrical system
- 1stFlrSF: First Floor square feet
- 2ndFlrSF: Second floor square feet
- LowQualFinSF: Low quality finished square feet (all floors)
- GrLivArea: Above grade (ground) living area square feet
- BsmtFullBath: Basement full bathrooms
- BsmtHalfBath: Basement half bathrooms
- FullBath: Full bathrooms above grade
- HalfBath: Half baths above grade
- Bedroom: Number of bedrooms above basement level
- Kitchen: Number of kitchens
- KitchenQual: Kitchen quality
- TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)
- Functional: Home functionality rating
- Fireplaces: Number of fireplaces
- FireplaceQu: Fireplace quality
- GarageType: Garage location
- GarageYrBlt: Year garage was built
- GarageFinish: Interior finish of the garage
- GarageCars: Size of garage in car capacity
- GarageArea: Size of garage in square feet
- GarageQual: Garage quality
- GarageCond: Garage condition
- PavedDrive: Paved driveway
- WoodDeckSF: Wood deck area in square feet
- OpenPorchSF: Open porch area in square feet
- EnclosedPorch: Enclosed porch area in square feet
- 3SsnPorch: Three season porch area in square feet
- ScreenPorch: Screen porch area in square feet
- PoolArea: Pool area in square feet
- PoolQC: Pool quality
- Fence: Fence quality
- MiscFeature: Miscellaneous feature not covered in other categories
- MiscVal: $Value of miscellaneous feature
- MoSold: Month Sold
- YrSold: Year Sold
- SaleType: Type of sale
- SaleCondition: Condition of sale

In [10]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [11]:
# Mendapatkan variabel yang mempuyai null value
df_train.isna().sum()[df_train.isna().sum()!=0]

LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

# Handle Missing Values
Cara Handle missing values dapat melalui
1. Average Value Method
2. Regression Method
3. ignore observation

Kita akan bagi cara handle missing values berdasarkan
1. Numerical Variable
2. Categorical Variabel

## 1. Handle Missing Values for Numerical Variable

<img src="images/house-prices-advanced-regression-techniques.png"/>

In [182]:
def HandleMissingValuesNumericalVar(variabel_name):
    from sklearn.linear_model import LinearRegression
    
    # Bagi data menjadi dua bagian besar yaitu null value dan not null value
    full_data = df_train[[variabel_name,"SalePrice"]]
    null_data = full_data[full_data[variabel_name].isnull()]
    notnull_data = full_data[~(full_data[variabel_name].isnull())]
    
    # Estimasi missing values via regresi
    x = np.array(notnull_data[variabel_name]).reshape(-1,1)
    y = np.array(notnull_data["SalePrice"])
    model = LinearRegression()
    fit = model.fit(x,y)
    b = fit.coef_
    a = fit.intercept_
    predict_x = (np.array(null_data["SalePrice"])-a)/b
    indeks = null_data.index.values.tolist()
    df_predict_x = pd.DataFrame(predict_x,index=indeks,columns=[variabel_name])
    df_y = pd.DataFrame(null_data["SalePrice"])
    
    #Create New Dataframe
    new_null_df = pd.concat([df_predict_x,df_y],ignore_index=True,axis=1)
    new_null_df.columns=[variabel_name,"SalePrice"]
    
    # Merge
    df_new = pd.concat([notnull_data,new_null_df]).sort_index()
    var = pd.DataFrame(df_new[variabel_name],columns=[variabel_name])

    return var

In [183]:
df_LotFrontage = HandleMissingValuesNumericalVar("LotFrontage")
df_LotFrontage.head()

   LotFrontage
0         65.0
1         80.0
2         68.0
3         60.0
4         84.0

## 2. Handle Missing Values for Categorical Variable

In [186]:
def HandleMissingValuesCategoricalVar(variable_name):
    from sklearn.linear_model import LogisticRegression
    
    # Bagi data menjadi dua bagian yaitu null_data dan non_null_data
    full_data=df_train[[variable_name,"SalePrice"]]
    null_data = full_data[full_data[variable_name].isnull() | (full_data[variable_name]=='None')]
    not_null_data = full_data[~(full_data[variable_name].isnull() | (full_data[variable_name]=='None'))]
    
    # Estimasi via regresi logistik
    y = np.array(not_null_data[variable_name])
    x = np.array(not_null_data['SalePrice']).reshape(-1,1)
    
    model = LogisticRegression()
    fit = model.fit(x,y)
    predict = fit.predict(np.array(null_data["SalePrice"]).reshape(-1,1))
    
    # Data Cleaning
    indeks = null_data.index.values.tolist()
    df_predict = pd.DataFrame(predict,index=indeks)
    y_null = pd.DataFrame(null_data["SalePrice"])  
    
    #Create New Dataframe
    new_null_df = pd.concat([df_predict,y_null],ignore_index=True,axis=1)
    new_null_df.columns = [variable_name,"SalePrice"]
    
    # Merge Data
    df_new = pd.concat([not_null_data,new_null_df]).sort_index()
    var = pd.DataFrame(df_new[variable_name],columns=[variable_name])

    return var

In [187]:
df_Alley = HandleMissingValuesCategoricalVar("Alley")
df_Alley.head()

  Alley
0  Pave
1  Pave
2  Pave
3  Pave
4  Pave

# 3. Handle Missing Values to all variable

In [156]:
null_var = df_train.isna().sum()[df_train.isna().sum() != 0].index.values.tolist()
cat_var = df_train.dtypes[df_train.dtypes == 'object'].index.values.tolist()
num_var = df_train.dtypes[df_train.dtypes != 'object'].index.values.tolist()

cat_null_var = [k for k in cat_var if k in null_var ]
num_null_var = [k for k in num_var if k in null_var ]

In [197]:
df = []
for k in num_null_var:
    df.append(HandleMissingValuesNumericalVar(k))
df_new_null_num_var = pd.concat([df[0],df[1],df[2]],axis=1)
df_new_null_num_var

      LotFrontage  MasVnrArea  GarageYrBlt
0            65.0       196.0       2003.0
1            80.0         0.0       1976.0
2            68.0       162.0       2001.0
3            60.0         0.0       1998.0
4            84.0       350.0       2000.0
...           ...         ...          ...
1455         62.0         0.0       1999.0
1456         85.0       119.0       1978.0
1457         66.0         0.0       1941.0
1458         68.0         0.0       1950.0
1459         75.0         0.0       1965.0

[1460 rows x 3 columns]

In [227]:
df = []
for k in cat_null_var:
    df.append(HandleMissingValuesCategoricalVar(k))
df_new_null_cat_var = pd.concat([df[0],df[1],df[2],df[3],df[4],
                                df[5],df[6],df[7],df[8],
                                df[9],df[10],df[11],df[12],
                                df[13],df[14],df[15]],axis=1)
df_new_null_cat_var

,Alley,MasVnrType,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PoolQC,Fence,MiscFeature
0,Pave,BrkFace,Gd,TA,No,GLQ,Unf,SBrkr,Gd,Attchd,RFn,TA,TA,Ex,MnPrv,Shed
1,Pave,BrkFace,Gd,TA,Gd,ALQ,Unf,SBrkr,TA,Attchd,RFn,TA,TA,Ex,MnPrv,Shed
2,Pave,BrkFace,Gd,TA,Mn,GLQ,Unf,SBrkr,TA,Attchd,RFn,TA,TA,Ex,MnPrv,Shed
3,Pave,BrkFace,TA,Gd,No,ALQ,Unf,SBrkr,Gd,Detchd,Unf,TA,TA,Ex,MnPrv,Shed
4,Pave,BrkFace,Gd,TA,Av,GLQ,Unf,SBrkr,TA,Attchd,RFn,TA,TA,Ex,MnPrv,Shed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,Pave,BrkFace,Gd,TA,No,Unf,Unf,SBrkr,TA,Attchd,RFn,TA,TA,Ex,MnPrv,Shed
1456,Pave,Stone,Gd,TA,No,ALQ,Rec,SBrkr,TA,Attchd,Unf,TA,TA,Ex,MnPrv,Shed
1457,Pave,BrkFace,TA,Gd,No,GLQ,Unf,SBrkr,Gd,Attchd,RFn,TA,TA,Ex,GdPrv,Shed
1458,Pave,BrkFace,TA,TA,Mn,GLQ,Rec,FuseA,Gd,Attchd,Unf,TA,TA,Ex,MnPrv,Shed
1459,Pave,BrkFace,TA,TA,No,BLQ,LwQ,SBrkr,Gd,Attchd,Fin,TA,TA,Ex,MnPrv,Shed

# 5. Merge Data

In [246]:
null_var = cat_null_var + num_null_var

In [247]:
var_lain = [k for k in df_train.columns.values.tolist() if k not in null_var ]

In [250]:
ALLDF = pd.concat([df_new_null_num_var,df_new_null_cat_var,df_train[var_lain]],axis=1)
ALLDF

,LotFrontage,MasVnrArea,GarageYrBlt,Alley,MasVnrType,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,65.0,196.0,2003.0,Pave,BrkFace,Gd,TA,No,GLQ,Unf,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,80.0,0.0,1976.0,Pave,BrkFace,Gd,TA,Gd,ALQ,Unf,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,68.0,162.0,2001.0,Pave,BrkFace,Gd,TA,Mn,GLQ,Unf,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,60.0,0.0,1998.0,Pave,BrkFace,TA,Gd,No,ALQ,Unf,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,84.0,350.0,2000.0,Pave,BrkFace,Gd,TA,Av,GLQ,Unf,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,62.0,0.0,1999.0,Pave,BrkFace,Gd,TA,No,Unf,Unf,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,85.0,119.0,1978.0,Pave,Stone,Gd,TA,No,ALQ,Rec,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,66.0,0.0,1941.0,Pave,BrkFace,TA,Gd,No,GLQ,Unf,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,68.0,0.0,1950.0,Pave,BrkFace,TA,TA,Mn,GLQ,Rec,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,75.0,0.0,1965.0,Pave,BrkFace,TA,TA,No,BLQ,LwQ,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [257]:
# Cek missing values
ALLDF.isna().sum()[ALLDF.isna().sum()!=0]

Series([], dtype: int64)

## 6. Reduksi Dimensi
Bertujuan untuk mengurangi variabel yang tidak signifikan berpengaruh terhadap model